[TTD_STR_INDUSTRY_NAME_COAL_MINE]
base = "Coal Mine"

[TTD_STR_INDUSTRY_NAME_COPPER_ORE_MINE]
base = "Copper Mine"

[TTD_STR_INDUSTRY_NAME_DIAMOND_MINE]
base = "Diamond Mine"

[TTD_STR_INDUSTRY_NAME_FOOD_PROCESSING_PLANT]
base = "Food Processing Plant"

[TTD_STR_INDUSTRY_NAME_FOREST]
base = "Forest"

[TTD_STR_INDUSTRY_NAME_FRUIT_PLANTATION]
base = "Fruit Plantation"

[TTD_STR_INDUSTRY_NAME_IRON_ORE_MINE]
base = "Iron Ore Mine"

[TTD_STR_INDUSTRY_NAME_OIL_REFINERY]
base = "Oil Refinery"

[TTD_STR_INDUSTRY_NAME_OIL_RIG]
base = "Oil Rig"

[TTD_STR_INDUSTRY_NAME_OIL_WELLS]
base = "Oil Wells"

[TTD_STR_INDUSTRY_NAME_PAPER_MILL]
base = "Paper Mill"

[TTD_STR_INDUSTRY_NAME_RUBBER_PLANTATION]
base = "Rubber Plantation"

[TTD_STR_INDUSTRY_NAME_SAWMILL]
base = "Sawmill"

[TTD_STR_INDUSTRY_NAME_STEEL_MILL]
base = "Steel Mill"

[TTD_STR_CARGO_PLURAL_COAL]
base = "Coal"

[TTD_STR_CARGO_PLURAL_COPPER_ORE]
base = "Copper Ore"

[TTD_STR_CARGO_PLURAL_DIAMONDS]
base = "Diamonds"

[TTD_STR_CARGO_PLURAL_FOOD]
base = "Food"

[TTD_STR_CARGO_PLURAL_GOODS]
base = "Goods"

[TTD_STR_CARGO_PLURAL_GRAIN]
base = "Grain"

[TTD_STR_CARGO_PLURAL_IRON_ORE]
base = "Iron Ore"

[TTD_STR_CARGO_PLURAL_LIVESTOCK]
base = "Livestock"

[TTD_STR_CARGO_PLURAL_MAIL]
base = "Mail"

[TTD_STR_CARGO_PLURAL_MAIZE]
base = "Maize"

[TTD_STR_CARGO_PLURAL_OIL]
base = "Oil"

[TTD_STR_CARGO_PLURAL_PAPER]
base = "Paper"

[TTD_STR_CARGO_PLURAL_PASSENGERS]
base = "Passengers"

[TTD_STR_CARGO_PLURAL_RUBBER]
base = "Rubber"

[TTD_STR_CARGO_PLURAL_SUGAR]
base = "Sugar"

[ECONOMY_INFO_FIRS]
base = "Complex economy with many industries and cargos."

[ECONOMY_INFO_BASIC_ARCTIC]
base = "Simple economy. Inspired by Finland, Northern Canada and Northern Siberia. Best used with Sub-Arctic climate."

[ECONOMY_INFO_BASIC_TEMPERATE]
base = "Simple economy. Inspired by south-western UK. Best used with Temperate climate."

[ECONOMY_INFO_BASIC_TROPIC]
base = "Simple economy. Inspired by Argentina, Peru and Chile. Best used with Sub-Tropic climate."

[ECONOMY_INFO_IN_A_HOT_COUNTRY]
base = "Complex economy with many industries and cargos. Inspired by central-western Africa. Best used with Sub-Tropic climate."

[ECONOMY_INFO_STEELTOWN]
base = "Complex economy featuring iron, steel and heavy manufacturing industries."

[CARGO_INFO_PASSENGERS]
base = "Available in all economies.  Produced and accepted by town buildings, and also a few industries."

[CARGO_INFO_MAIL]
base = "Available in all economies.  Produced and accepted by town buildings."

[CARGO_INFO_ACID]
base = "Industrial acids, such as hydrochloric, nitric and sulphuric acid."

[CARGO_INFO_AGGREGATES]
base = "Gravel, sand, crushed stone and similar materials used in construction."

[CARGO_INFO_ALCOHOL]
base = "Wine, beer, cider, spirits."

[CARGO_INFO_ALUMINIUM]
base = "Refined Aluminium metal, in coils, ingots, slabs etc."

[CARGO_INFO_AMMONIA]
base = "Widely used industrial chemical. Transported as liquid or cryogenically as liquified compressed gas."

[CARGO_INFO_BASE_METALS]
base = "Non-ferrous metals, such as copper, nickel, zinc and lead."

[CARGO_INFO_BAUXITE]
base = "Bauxite ore / alumina."

[CARGO_INFO_BEANS]
base = "Common beans, fava beans, soybeans and similar edible legumes."

[CARGO_INFO_BUILDING_MATERIALS]
base = "Cement, glass, metal components, wood products, pipes and similar construction materials."

[CARGO_INFO_CASSAVA]
base = "Edible root crop, also known as manioc and yuca."

[CARGO_INFO_CARBON_BLACK]
base = "Intensely black carbon powder, used in tyres, plastics and pigments.  Handled as a powder."

[CARGO_INFO_CARBON_STEEL]
base = "Billets, blooms, ingots and slabs."

[CARGO_INFO_CAST_IRON]
base = "Billets, blooms, ingots and slabs."

[CARGO_INFO_CEMENT]
base = "Dry cement in powder or clinker form."

[CARGO_INFO_CHEMICALS]
base = "Generic chemicals, usually in liquid form."

[CARGO_INFO_CHLORINE]
base = "Industrial chemical, usually transported cryogenically as liquified compressed gas."

[CARGO_INFO_CLAY]
base = "Generic clays, for producing building materials and other industrial uses."

[CARGO_INFO_CLEANING_AGENTS]
base = "Chemicals, soaps, scouring agents etc for industrial and domestic use. Primarily liquid, can also be powder or solid (such as shot blasting sand)."

[CARGO_INFO_COAL_TAR]
base = "By-product from coke production, a thick slow-flowing liquid."

[CARGO_INFO_COFFEE]
base = "Raw or roasted coffee beans."

[CARGO_INFO_COKE]
base = "Coal that has been heated in a coke oven, producing a fuel that is nearly pure carbon."

[CARGO_INFO_CONCRETE_PRODUCTS]
base = "Cast products such as blocks, beams and panels. Can also be handled as ready-mix concrete in mixer trucks."

[CARGO_INFO_COPPER]
base = "Refined Copper metal, in coils, ingots etc."

[CARGO_INFO_CRANES_AND_HOISTS]
base = "Cranes, hoists, elevators and similar vertical lifting machines for use in industry, buildings, workshops etc."

[CARGO_INFO_DIAMONDS]
base = "Are forever, etc."

[CARGO_INFO_EDIBLE_OIL]
base = "Oil for cooking and consumption."

[CARGO_INFO_ELECTRICAL_PARTS]
base = "Electrical and electronic components, motors, controllers, switchgear, lights etc."

[CARGO_INFO_ENGINEERING_SUPPLIES]
base = "Machinery, fuel, parts, wood products, pipes, explosives and other supplies for mines and similar industries."

[CARGO_INFO_EXPLOSIVES]
base = "Civil explosives for mining, construction etc."

[CARGO_INFO_FARM_SUPPLIES]
base = "Machinery, fuel, parts, fertiliser and other supplies for farms, forests and similar industries."

[CARGO_INFO_FERROALLOYS]
base = "Used in steel production. Alloys of iron and other elements including manganese, nickel, chromium, aluminium, silicon and tungsten.  Grey lumps, similar in size and shape to coal lumps."

[CARGO_INFO_FERROCHROME]
base = "Used in alloy and stainless steel production, an alloy of chromium and iron.  Grey lumps, similar in size and shape to coal lumps."

[CARGO_INFO_FORGINGS_AND_CASTINGS]
base = "Metal parts for assembly into larger items."

[CARGO_INFO_GRAIN]
base = "Wheat, barley etc."

[CARGO_INFO_HARDWARE]
base = "For household and construction use. Tools, utensils, fixtures, fittings, in metal and other materials."

[CARGO_INFO_LIFTING_EQUIPMENT]
base = "Drums, winches, shackles, hooks, pulleys, hydraulic rams and other parts for cranes, hoists, elevators etc."

[CARGO_INFO_LIVESTOCK]
base = "Mostly cows, pigs and sheep for meat production.  Other animals may also be eaten."

[CARGO_INFO_LYE]
base = "Industrial chemical. Also known as Lye or Caustic Soda. Usually transported as liquid."

[SEALS_HOSES_AND_BELTS]
base = "Flexible seals, gaskets, hoses, belts, mats, bushings, etc, made from rubber or similar materials."

[CARGO_INFO_TIMBER]
base = "Processed wood products from a sawmill."

[CARGO_INFO_KAOLIN]
base = "Industrial mineral, also known as Kaolin, used primarily in paper and plastics production."

[CARGO_INFO_MANGANESE]
base = "Manganese ore, used primarily in steel production."

[CARGO_INFO_PACKAGING]
base = "Boxes, bottles, jars, cans, etc."

[CARGO_INFO_MARINE_SUPPLIES]
base = "Machinery, parts, fuel, construction materials and other supplies for harbours, docks and similar industries."

[CARGO_INFO_METAL]
base = "Generic metal, such as steel, aluminium or other common metals."

[CARGO_INFO_NITROGEN]
base = "Industrial gas. Transported cryogenically as liquified compressed gas."

[CARGO_INFO_OXYGEN]
base = "Industrial gas. Transported cryogenically as liquified compressed gas."

[CARGO_INFO_PEAT]
base = "Biomass from peat bogs, extracted for fuel and horticulture."

[CARGO_INFO_PIG_IRON]
base = "Basic iron from a blast furnace, as molten liquid or solid ingots."

[CARGO_INFO_PLANT_FIBRES]
base = "Cotton, flax, jute and similar materials, for producing textiles and composite materials."

[CARGO_INFO_PETROL]
base = "Petrol, diesel and similar fuels."

[CARGO_INFO_PLASTICS]
base = "Raw plastic for futher processing. Usually transported as resin beads."

[CARGO_INFO_PIPEWORK]
base = "Pipe assemblies with valves, pumps etc attached, for construction and industrial use."

[CARGO_INFO_PYRITE_ORE]
base = "Sulfide minerals, smelted to produce a variety of industrial products."

[CARGO_INFO_QUICKLIME]
base = "Calcium Oxide, also known as burnt lime. Transported as fine powder that must be kept dry."

[CARGO_INFO_REBAR]
base = "Thin rough steel bars widely used to reinforce concrete structures. Transported as coils or bundles of straight bars."

[CARGO_INFO_RUBBER]
base = "Mostly natural latex."

[CARGO_INFO_SALT]
base = "Widely used industrial chemical. Usually transported as bulk cargo that must be kept dry."

[CARGO_INFO_SAND]
base = "Coarse sand for construction, or fine silica sand for glass-making and metal casting. Transported as bulk or powder."

[CARGO_INFO_SLAG]
base = "Waste product from iron and steel production."

[CARGO_INFO_SODA_ASH]
base = "Industrial chemical. White powder form."

[CARGO_INFO_STEEL_BILLETS_AND_BLOOMS]
base = "Semi-finished steel castings. Rectangular, square or round in cross-section."

[CARGO_INFO_STEEL_INGOTS]
base = "Rough steel castings, requiring further processing. Ingots may be small or very large. Typical ingot profiles are rectangular or round."

[CARGO_INFO_STEEL_MERCHANT_BAR]
base = "Steel bars, as rounds, squares, flats and other profiles. Transported as long straight products."

[CARGO_INFO_STEEL_PIPE]
base = "Long round steel pipes for transporting liquids in pipelines, buildings, industries etc."

[CARGO_INFO_STEEL_SECTIONS]
base = "Rolled steel plates and sections - I beams, H beams, channels etc. Transported as flat plates or long straight products."

[CARGO_INFO_STEEL_SHEET]
base = "Thin rolled steel sheet and strip, widely used to fabricate other products. Transported as flat sheets or as coils."

[CARGO_INFO_STEEL_SLAB]
base = "Semi-finished steel castings. Always flat and rectangular in cross-section."

[CARGO_INFO_STEEL_TUBE]
base = "Long hollow tube in round, rectangular and other cross-sections. Used for fabricating structures and machinery."

[CARGO_INFO_STEEL_WIRE_ROD]
base = "Steel wire and thin rods. Primarily transported as coils."

[CARGO_INFO_STEEL_WIRE_ROPE]
base = "Ropes and cables produced by drawing steel wire rod to a smaller diameter, then twisting into bundled ropes."

[CARGO_INFO_SULPHUR]
base = "Widely used industrial chemical. Bright yellow, in powder or liquid form."

[CARGO_INFO_TIN]
base = "Ingots."

[CARGO_INFO_TYRE_CORD]
base = "Fine wire used to reinforce tyres. Transported as coil."

[CARGO_INFO_VEHICLE_BODIES]
base = "Cabs, bonnets, doors and similar body structures for vehicle production."

[CARGO_INFO_VEHICLE_ENGINES]
base = "Internal combustion engines and related powertrain parts such as gearboxes."

[CARGO_INFO_VEHICLE_PARTS]
base = "Components for vehicle production such as powertrain components, chassis and suspension components, electrical parts, external trim and interior parts."

[CARGO_INFO_VEHICLES]
base = "Mostly trucks. Or cars. Or light trucks."

[CARGO_INFO_WELDING_CONSUMABLES]
base = "Supplies for cutting and welding metal, such as welding rods, tools, and industrial gases including acetylene, argon, propane, oxygen and nitrogen."

[CARGO_INFO_WOOD]
base = "Logs from a forest."

[CARGO_INFO_WOOL]
base = "Bales."

[CARGO_INFO_ZINC]
base = "Ingots."

[INDUSTRY_INFO_GRAIN_MILL]
base = "Two types. Windmill variant available until 1900."
