[GLOBAL_PRAGMA]
grflangid = "0x22"
plural = "0"
gender = "Masculin Femenin"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Industry Replacement Set{}{BLACK}Fet per andythenorth, FooBar, planetmaker, Terkhen i Yexo, amb l'ajuda de molts altres. {SILVER}Consulteu el llegeix-me per a més informació, incloent-hi com usar FIRS. {BLACK}Llicència: GPL v2."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Màxima distància en caselles des de caladors de pesca, plataformes petrolíferes i zones de dragatge fins la costa."

[STR_PARAM_DESC_ECONOMIES]
base = "Cada model d'economia ofereix una combinació diferent de càrregues i indústries.{}{}Per als jugadors que cerquin un estil de joc senzill, les economies \"bàsiques\" contenen menys tipus d'indústries i de càrregues."

[STR_PARAM_DESC_NO_OPENINGS]
base = "Per defecte, durant el joc s'aniran obrint noves indústries.{}{}Si activeu l'impediment d'aparició d'indústries, no se n'obriran durant el joc, i els jugadors no podran financiar-ne ni prospeccionar-ne de noves."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Màxima distància a la costa en caselles per a les indústries marines"

[STR_PARAM_NAME_ECONOMIES]
base = "Economia"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Impedeix l'aparició d'indústries durant el joc"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Sense límit"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Economia Bàsica Temperada"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "Economia Bàsica Àrtica"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Economia Bàsica Tropical"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "Heart of Darkness"

[STR_CARGO_NAME_ALCOHOL]
base = "{G=Masculin}Alcohol"

[STR_CARGO_NAME_BAUXITE]
base = "{G=Femenin}Bauxita"

[STR_CARGO_NAME_BEANS]
base = "Bajoques"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "{G=Masculin}Materials de construcció"

[STR_CARGO_NAME_CHEMICALS]
base = "{G=Masculin}Productes químics"

[STR_CARGO_NAME_CLAY]
base = "{G=Femenin}Argila"

[STR_CARGO_NAME_COFFEE]
base = "Cafè"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "{G=Masculin}Subministraments tècnics"

[STR_CARGO_NAME_FIBRES]
base = "{G=Femenin}Fibres vegetals"

[STR_CARGO_NAME_FISH]
base = "{G=Masculin}Peix"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "{G=Masculin}Subministraments agrícoles"

[STR_CARGO_NAME_FRUITS]
base = "{G=Femenin}Fruita"

[STR_CARGO_NAME_TIMBER]
base = "{G=Masculin}Taulons"

[STR_CARGO_NAME_METAL]
base = "{G=Masculin}Metall"

[STR_CARGO_NAME_MILK]
base = "{G=Femenin}Llet"

[STR_CARGO_NAME_NITRATES]
base = "Nitrats"

[STR_CARGO_NAME_PETROL]
base = "{G=Femenin}Gasolina"

[STR_CARGO_NAME_RECYCLABLES]
base = "{G=Femenin}Deixalles"

[STR_CARGO_NAME_SAND]
base = "{G=Femenin}Sorra"

[STR_CARGO_NAME_SCRAP_METAL]
base = "{G=Femenin}Ferralla"

[STR_CARGO_NAME_AGGREGATES]
base = "{G=Femenin}Pedres"

[STR_CARGO_NAME_SUGAR_BEET]
base = "{G=Femenin}Remolatxa"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "Parts de vehicles"

[STR_CARGO_NAME_WOOL]
base = "{G=Femenin}Llana"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} d'alcohol"

[STR_CARGO_UNIT_BAUXITE]
base = "{WEIGHT} de bauxita"

[STR_CARGO_UNIT_BEANS]
base = "{WEIGHT} de bajoques"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} de materials de construcció"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} de productes químics"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} d'argila"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} sac{P 0 \"\" s} de cafè"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} caix{P 0 a es} de subministraments tècnics"

[STR_CARGO_UNIT_FIBRES]
base = "{SIGNED_WORD} bal{P 0 a es} de fibres vegetals"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} de peix"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} caix{P 0 a es} de subministraments agrícoles"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} de fruita"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} de taulons"

[STR_CARGO_UNIT_METAL]
base = "{WEIGHT} de metall"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} de llet"

[STR_CARGO_UNIT_NITRATES]
base = "{WEIGHT} de nitrats"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} de gasolina"

[STR_CARGO_UNIT_RECYCLABLES]
base = "{WEIGHT} de deixalles"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} de sorra"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} de ferralla"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} de pedres"

[STR_CARGO_UNIT_SUGAR_BEET]
base = "{WEIGHT} de remolatxa"

[STR_CARGO_UNIT_VEHICLE_PARTS]
base = "{SIGNED_WORD} caix{P 0 a es} de parts de vehicles"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} bal{P 0 a es} de llana"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BAUXITE]
base = "{TINYFONT}BX"

[STR_CID_BEANS]
base = "{TINYFONT}BJ"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}MC"

[STR_CID_CHEMICALS]
base = "{TINYFONT}PQ"

[STR_CID_CLAY]
base = "{TINYFONT}AR"

[STR_CID_COFFEE]
base = "{TINYFONT}CF"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}ST"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}SA"

[STR_CID_FIBRES]
base = "{TINYFONT}FV"

[STR_CID_FISH]
base = "{TINYFONT}PE"

[STR_CID_TIMBER]
base = "{TINYFONT}TA"

[STR_CID_METAL]
base = "{TINYFONT}MT"

[STR_CID_MILK]
base = "{TINYFONT}LE"

[STR_CID_NITRATES]
base = "{TINYFONT}NI"

[STR_CID_PETROL]
base = "{TINYFONT}GA"

[STR_CID_RECYCLABLES]
base = "{TINYFONT}DE"

[STR_CID_SAND]
base = "{TINYFONT}SO"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}FL"

[STR_CID_AGGREGATES]
base = "{TINYFONT}PE"

[STR_CID_SUGAR_BEET]
base = "{TINYFONT}RE"

[STR_CID_VEHICLE_PARTS]
base = "{TINYFONT}PV"

[STR_CID_WOOL]
base = "{TINYFONT}LA"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS no està dissenyat per al paisatge de joguines"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "s'ha de situar sota l'estatge de les neus."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "s'ha de situar en terra ferma."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "no es pot situar al desert."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "no es pot situar en terreny inclinat."

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "només es permet una indústria d'aquest tipus a cada població."

[STR_IND_ALUMINIUM_PLANT]
base = "{G=Femenin}Planta d'alumini"

[STR_IND_ARABLE_FARM]
base = "{G=Femenin}Granja de conreu"

[STR_IND_ASSEMBLY_PLANT]
base = "Fàbrica de vehicles"

[STR_IND_BIOREFINERY]
base = "{G=Femenin}Biorefineria"

[STR_IND_BREWERY]
base = "{G=Femenin}Cerveseria"

[STR_IND_CIDER_MILL]
base = "Molí de sidra"

[STR_IND_BRICK_WORKS]
base = "{G=Femenin}Fàbrica de maons"

[STR_IND_BUILDERS_YARD]
base = "{G=Femenin}Constructora"

[STR_IND_BULK_TERMINAL]
base = "Terminal de mercaderies voluminoses"

[STR_IND_CEMENT_PLANT]
base = "{G=Femenin}Fàbrica de ciment"

[STR_IND_CHEMICAL_PLANT]
base = "{G=Femenin}Planta química"

[STR_IND_CLAY_PIT]
base = "{G=Femenin}Argilera"

[STR_IND_COFFEE_ESTATE]
base = "Hisenda de cafè"

[STR_IND_DAIRY]
base = "{G=Femenin}Indústria làctia"

[STR_IND_DREDGING_SITE]
base = "{G=Femenin}Zona de dragatge"

[STR_IND_FISHING_GROUND]
base = "{G=Masculin}Calador de pesca"

[STR_IND_FISHING_HARBOUR]
base = "{G=Masculin}Port pesquer"

[STR_IND_FOOD_MARKET]
base = "{G=Masculin}Mercat"

[STR_IND_FOOD_PROCESSOR]
base = "{G=Femenin}Planta de processament d'aliments"

[STR_IND_FURNITURE_FACTORY]
base = "{G=Femenin}Fàbrica de mobles"

[STR_IND_GENERAL_STORE]
base = "Petit comerç"

[STR_IND_GLASS_WORKS]
base = "{G=Femenin}Vidrieria"

[STR_IND_HARDWARE_STORE]
base = "{G=Femenin}Ferreteria"

[STR_IND_HOTEL]
base = "{G=Masculin}Hotel"

[STR_IND_IRON_WORKS]
base = "{G=Femenin}Farga"

[STR_IND_SCRAP_YARD]
base = "{G=Masculin}Desballestador"

[STR_IND_LIME_KILN]
base = "{G=Masculin}Forn de calç"

[STR_IND_TIMBER_YARD]
base = "{G=Femenin}Fusteria"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "{G=Femenin}Fàbrica de maquinària"

[STR_IND_MIXEDFARM]
base = "{G=Femenin}Granja mixta"

[STR_IND_NITRATE_MINE]
base = "{G=Femenin}Mina de nitrats"

[STR_IND_ORCHARD_PIGGERY]
base = "Arbres fruiters i granja de porcs"

[STR_IND_PETROLPUMP]
base = "{G=Femenin}Gasolinera"

[STR_IND_PLASTICS_PLANT]
base = "{G=Femenin}Fàbrica de plàstics"

[STR_IND_PORT]
base = "{G=Masculin}Port"

[STR_IND_POWER_PLANT]
base = "{G=Femenin}Central elèctrica"

[STR_IND_QUARRY]
base = "{G=Femenin}Pedrera"

[STR_IND_RANCH]
base = "Ranxo"

[STR_IND_RECYCLING_DEPOT]
base = "{G=Femenin}Deixalleria"

[STR_IND_RECYCLING_PLANT]
base = "{G=Femenin}Planta de reciclatge"

[STR_IND_SHEEPFARM]
base = "{G=Femenin}Granja ovina"

[STR_IND_SMITHY_FORGE]
base = "{G=Femenin}Ferreria"

[STR_IND_STOCKYARD]
base = "{G=Masculin}Escorxador"

[STR_IND_SUGAR_REFINERY]
base = "{G=Femenin}Sucreria"

[STR_IND_TEXTILE_MILL]
base = "{G=Femenin}Fàbrica tèxtil"

[STR_IND_TRADING_POST]
base = "Botiga de queviures"

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}Producció actual: {YELLOW}normal{}{}{BLACK}Per a doblar la producció cal que lliureu {SIGNED_WORD} caixes de subministraments en tres mesos (o {SIGNED_WORD} caixes per a producció quàdruple)"

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}Producció actual: {YELLOW}millorada (doble){}{}{BLACK}Per a mantenir aquest nivell cal que lliureu {SIGNED_WORD} caixes de subministraments en tres mesos, o {SIGNED_WORD} caixes per aconseguir producció quàdruple"

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}Producció actual: {YELLOW}entusiasta (quàdruple){}{}{BLACK}Per a mantenir aquest nivell cal que lliureu {SKIP}{SIGNED_WORD} caixes de subministraments en tres mesos"

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}Producció actual: {YELLOW}Normal{}{}{BLACK}Per a doblar la producció cal que lliureu {SIGNED_WORD} unitats de càrrega en tres mesos{}Per a quadrupicar-la, lliureu {SIGNED_WORD} unitats de càrrega en tres mesos"

[STR_PORT_PRODUCTION_2X]
base = "{BLACK}Producció actual: {YELLOW}millorada (doble){}{}{BLACK}Per a mantenir aquest nivell cal que lliureu {SIGNED_WORD} unitats de càrrega en tres mesos, o {SIGNED_WORD} per a quadruplicar-la"

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Producció actual: {YELLOW}Gung ho (quàdruple){}{}{BLACK}Per a mantenir aquest nivell cal que lliureu {SKIP}{SIGNED_WORD} unitats de càrrega en tres mesos"

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Localització: {YELLOW}No es pot situar a la neu ni al desert."

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Ubicació: {YELLOW}No es pot fundar en terreny nevat ni en deserts."

[STR_FUND_DAIRY_FARM]
base = "{}{BLACK}Ubicació: {YELLOW}No es pot fundar en terreny nevat ni en deserts."

[STR_FUND_FOREST]
base = "{}{BLACK}Localització: {YELLOW}No es pot situar al desert."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Localització: {YELLOW}No es pot situar a la neu."

[STR_FUND_ORCHARD_PIGGERY]
base = "{}{BLACK}Ubicació: {YELLOW}No es pot fundar en terreny nevat ni en deserts."

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}Ubicació: {YELLOW}No es pot fundar en terreny nevat ni en deserts."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Disponible des de: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}No disponible després de: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_ANIMALS]
base = "Mercat de cavalls"

[STR_STATION_FARM_1]
base = "Mansió"

[STR_STATION_FISHMARKET]
base = "Llotja de peix"

[STR_STATION_INDUSTRY_ESTATE_1]
base = "Parc industrial"

[STR_STATION_INDUSTRY_HARBOUR_1]
base = "Port industrial"

[STR_STATION_MARKET]
base = "Mercat"

[STR_STATION_MILL]
base = "Molí"

[STR_STATION_MINE]
base = "Carrer de l'adoberia"

[STR_STATION_PIT]
base = "Pedrera"

[STR_STATION_PLANTATION]
base = "Plantació"

[STR_STATION_POWERHUNGRY]
base = "Central elèctrica"

[STR_STATION_REFINERY]
base = "Refineria"

[STR_STATION_TOWN_1]
base = "Antic ajuntament"

[STR_STATION_WATER]
base = "Banc de sorra"
