[GLOBAL_PRAGMA]
grflangid = "0x28"
plural = "0"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Industry Replacement Set{}{BLACK}Publicat de andythenorth, FooBar, planetmaker, Terkhen şi Yexo, cu ajutorul miultor altora. {SILVER}Vezi fişierul readme pentru mai multe informaţii, inclusiv cum să foloseşti FIRS. {BLACK}License: GPL v2."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Distanţa maximă a zonelor de pescuit, a sondelor petroliere şi zonelor de dragare faţă de coastă."

[STR_PARAM_DESC_ECONOMIES]
base = "Când va fi gata, FIRS va oferi posibilitatea de a alege industriile. Încărcăturile şi industriile pot varia în fiecare economie. Cotele de plată ale mărfurilor pot fi diferite pentru fiecare economie.{}{}{SILVER}Deocamdată este disponibilă o singură economie. :)"

[STR_PARAM_DESC_NO_OPENINGS]
base = "Cu setările predefinite, noi industrii vor apărea în timpul jocului.{}{}Dacă este activat acest parametru, industriile noi nu vor apărea pe durata jocului iar jucătorii nu vor avea posibilitatea de explorare şi exploatare a acestora."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Distanţa maximă de coastă a industriilor marine"

[STR_PARAM_NAME_ECONOMIES]
base = "Economie"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Împiedică apariţia noilor industrii în timpul jocului"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Fără limită"

[STR_CARGO_NAME_ALCOHOL]
base = "Alcool"

[STR_CARGO_NAME_BAUXITE]
base = "Bauxită"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Materiale de construcţii"

[STR_CARGO_NAME_CHEMICALS]
base = "Produse chimice"

[STR_CARGO_NAME_CLAY]
base = "Lut"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Echipament de inginerie"

[STR_CARGO_NAME_FIBRES]
base = "Fibre vegetale"

[STR_CARGO_NAME_FISH]
base = "Peşte"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Produse agricole"

[STR_CARGO_NAME_FRUITS]
base = "Fructe"

[STR_CARGO_NAME_TIMBER]
base = "Cherestea"

[STR_CARGO_NAME_METAL]
base = "Metal"

[STR_CARGO_NAME_MILK]
base = "Lapte"

[STR_CARGO_NAME_PETROL]
base = "Petrol"

[STR_CARGO_NAME_RECYCLABLES]
base = "Produse reciclabile"

[STR_CARGO_NAME_SAND]
base = "Nisip"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Deşeuri metalice"

[STR_CARGO_NAME_AGGREGATES]
base = "Piatră"

[STR_CARGO_NAME_SUGAR_BEET]
base = "Sfeclă de zahăr"

[STR_CARGO_NAME_WOOL]
base = "Lână"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} de alcool"

[STR_CARGO_UNIT_BAUXITE]
base = "{WEIGHT} de bauxită"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} materiale de construcţii"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} de chimicale"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} de lut"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} cutii cu echipamente de inginerie"

[STR_CARGO_UNIT_FIBRES]
base = "{SIGNED_WORD} baloţi fibre vegetale"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} de peşte"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} cutii cu produse agricole"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} de fructe"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} de cherestea"

[STR_CARGO_UNIT_METAL]
base = "{WEIGHT} de metal"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} de lapte"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} de petrol"

[STR_CARGO_UNIT_RECYCLABLES]
base = "{WEIGHT} de produse reciclabile"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} de nisip"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} de deşeuri metalice"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} de piatră"

[STR_CARGO_UNIT_SUGAR_BEET]
base = "{WEIGHT} de sfeclă de zahăr"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} baloţi de lână"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BAUXITE]
base = "{TINYFONT}BX"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}MC"

[STR_CID_CHEMICALS]
base = "{TINYFONT}CH"

[STR_CID_CLAY]
base = "{TINYFONT}LT"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}EI"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}PA"

[STR_CID_FIBRES]
base = "{TINYFONT}FV"

[STR_CID_FISH]
base = "{TINYFONT}PE"

[STR_CID_TIMBER]
base = "{TINYFONT}CR"

[STR_CID_METAL]
base = "{TINYFONT}MT"

[STR_CID_MILK]
base = "{TINYFONT}LT"

[STR_CID_PETROL]
base = "{TINYFONT}PT"

[STR_CID_RECYCLABLES]
base = "{TINYFONT}RC"

[STR_CID_SAND]
base = "{TINYFONT}SA"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}DM"

[STR_CID_AGGREGATES]
base = "{TINYFONT}PR"

[STR_CID_SUGAR_BEET]
base = "{TINYFONT}SZ"

[STR_CID_WOOL]
base = "{TINYFONT}LN"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS nu a fost conceput pentru a fi folosit pe climatul Toyland"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "trebuie amplasat sub linia de zăpadă."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "trebuie amplasat pe uscat."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "nu poate fi amplasat în deşert."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "nu poate fi amplasat în pantă."

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "este permisă o singură industrie de acest gen pentru un oraş."

[STR_IND_ALUMINIUM_PLANT]
base = "Fabrică de aluminiu"

[STR_IND_ARABLE_FARM]
base = "Fermă arabilă"

[STR_IND_BIOREFINERY]
base = "Rafinărie biologică"

[STR_IND_BREWERY]
base = "Fabrică de bere"

[STR_IND_BRICK_WORKS]
base = "Fabrică de cărămidă"

[STR_IND_BUILDERS_YARD]
base = "Şantier de construcţie"

[STR_IND_CEMENT_PLANT]
base = "Fabrică de ciment"

[STR_IND_CLAY_PIT]
base = "Groapă de lut"

[STR_IND_DAIRY]
base = "Fabrică de lapte"

[STR_IND_DREDGING_SITE]
base = "Dragaj"

[STR_IND_FISHING_GROUND]
base = "Zonă de pescuit"

[STR_IND_FISHING_HARBOUR]
base = "Port pescăresc"

[STR_IND_FOOD_MARKET]
base = "Băcănie"

[STR_IND_FURNITURE_FACTORY]
base = "Fabrică de mobilă"

[STR_IND_GLASS_WORKS]
base = "Fabrică de sticlă"

[STR_IND_HARDWARE_STORE]
base = "Magazin de hardware"

[STR_IND_HOTEL]
base = "Hotel"

[STR_IND_IRON_WORKS]
base = "Fierărie"

[STR_IND_SCRAP_YARD]
base = "Groapă de gunoi"

[STR_IND_LIME_KILN]
base = "Cuptor de var"

[STR_IND_TIMBER_YARD]
base = "Fabrică de cherestea"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "Magazin auto"

[STR_IND_MIXEDFARM]
base = "Fermă mixtă"

[STR_IND_PETROLPUMP]
base = "Staţie de petrol"

[STR_IND_PLASTICS_PLANT]
base = "Fabrică de materiale plastice"

[STR_IND_QUARRY]
base = "Carieră"

[STR_IND_RECYCLING_DEPOT]
base = "Depozit de materiale reciclabile"

[STR_IND_RECYCLING_PLANT]
base = "Fabrică de reciclarea materialelor"

[STR_IND_SHEEPFARM]
base = "Fermă de oi"

[STR_IND_SMITHY_FORGE]
base = "Potcovărie"

[STR_IND_STOCKYARD]
base = "Þarc de vite"

[STR_IND_SUGAR_REFINERY]
base = "Rafinărie de zahăr"

[STR_IND_TEXTILE_MILL]
base = "Fabrică de textile"

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Locaţie: {YELLOW}nu poate fi construit pe zăpadă sau în deşert."

[STR_FUND_FOREST]
base = "{}{BLACK}Locaţie: {YELLOW}nu poate fi construitîn deşert."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Locaţie: {YELLOW}nu poate fi construit pe zăpadă."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Disponibil din: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}Indisponibil după: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"
