[GLOBAL_PRAGMA]
grflangid = "0x00"
plural = "0"

[STR_CARGO_NAME_FIBRES]
base = "Plant Fibers"

[STR_CARGO_NAME_TIMBER]
base = "Lumber"

[STR_CARGO_NAME_PETROL]
base = "Petroleum Fuels"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} sack{P 0 \"\" s} of coffee"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} crate{P 0 \"\" s} of engineering supplies"

[STR_CARGO_UNIT_FIBRES]
base = "{SIGNED_WORD} bale{P 0 \"\" s} of plant fibers"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} crate{P 0 \"\" s} of farm supplies"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} of lumber"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} of petroleum fuels"

[STR_CARGO_UNIT_VEHICLE_PARTS]
base = "{SIGNED_WORD} crate{P 0 \"\" s} of vehicle parts"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} bale{P 0 \"\" s} of wool"

[STR_CID_CASSAVA]
base = "{TINYFONT}CA"

[STR_CID_VEHICLES]
base = "{TINYFONT}VH"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS is not designed to be used with Toyland climate"

[STR_IND_ALUMINIUM_PLANT]
base = "Aluminum Plant"

[STR_IND_DREDGING_SITE]
base = "Dredging Site"

[STR_IND_FISHING_HARBOUR]
base = "Fishing Harbor"

[STR_IND_FOOD_MARKET]
base = "Grocery Store"

[STR_IND_SCRAP_YARD]
base = "Junk Yard"

[STR_IND_TIMBER_YARD]
base = "Lumber Yard"

[STR_IND_MACHINE_SHOP]
base = "Machine Shop"

[STR_IND_PETROLPUMP]
base = "Gas Station"

[STR_IND_POWER_PLANT]
base = "Power Plant"

[STR_IND_TYRE_PLANT]
base = "Tire Plant"

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}Current production: {YELLOW}Normal{}{}{BLACK}For {WHITE}Enhanced {BLACK}production deliver {SIGNED_WORD} units of cargo within three months{}For {WHITE}Gung-ho {BLACK}production deliver {SIGNED_WORD} units"

[STR_FUND_FOREST]
base = "{}{BLACK}Location: {YELLOW}Cannot be funded in deserts."

[STR_STATION_INDUSTRY_HARBOUR_1]
base = "Industrial Harbor"
